version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 60:60
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - php
      - composer
  mysql:
    build:
      context: .
      dockerfile: mysql.dockerfile
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    build:
      context: .
      dockerfile: npm.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html
  # test:
  #   build:
  #     context: .
  #     dockerfile: php.test.dockerfile
  #   volumes:
  #     - ./src:/var/www/html
  #   entrypoint: ["/var/www/html/artisan", "test", "--coverage-html", "/var/www/html/storage/framework/testing/coverage"]
  #   working_dir: /var/www/html
